# Generated by Django 4.1.7 on 2023-04-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='newsletter_sub',
            field=models.BooleanField(default=False),
        ),
    ]
