# Generated by Django 4.1.7 on 2023-02-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0011_rename_game_dlc_required_game_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('slug', models.SlugField(max_length=254)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('landing_page', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, max_length=1024, null=True)),
                ('apply_to', models.ManyToManyField(limit_choices_to={'in_promo': False}, related_name='games.DLC+', to='games.game')),
            ],
        ),
    ]
