# Generated by Django 4.1.7 on 2023-02-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_rename_price_dlc_base_price_and_more'),
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='apply_to',
            field=models.ManyToManyField(related_name='games.DLC+', to='games.game'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='slug',
            field=models.SlugField(blank=True, max_length=254, null=True),
        ),
    ]
