# Generated by Django 4.1.7 on 2023-03-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_alter_promo_apply_to_alter_promo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
