# Generated by Django 4.1.7 on 2023-03-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_alter_game_promo_percentage'),
        ('promo', '0003_promo_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='apply_to',
        ),
        migrations.AddField(
            model_name='promo',
            name='apply_to_dlc',
            field=models.ManyToManyField(related_name='mtm', to='games.dlc'),
        ),
        migrations.AddField(
            model_name='promo',
            name='apply_to_game',
            field=models.ManyToManyField(related_name='mtm', to='games.game'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
