# Generated by Django 4.1.7 on 2023-03-12 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_alter_dlc_media_alter_dlc_tags_alter_game_media_and_more'),
        ('promo', '0006_promo_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='media',
        ),
        migrations.AddField(
            model_name='promo',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.media'),
        ),
    ]
