# Generated by Django 4.1.7 on 2023-03-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0007_remove_promo_media_promo_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='long_description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='short_description',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
