# Generated by Django 4.1.7 on 2023-03-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0008_promo_long_description_promo_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='long_description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='short_description',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
