# Generated by Django 4.1.7 on 2023-04-16 12:26

from django.db import migrations, models
import django.db.models.deletion
import promo.utils


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0030_alter_userrating_value'),
        ('promo', '0008_promo_long_description_promo_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='apply_to_dlc',
            field=models.ManyToManyField(blank=True, related_name='dlcset', to='games.dlc'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='apply_to_game',
            field=models.ManyToManyField(blank=True, related_name='gameset', to='games.game'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='end_date',
            field=models.DateTimeField(default=promo.utils.default_end_datetime, null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='long_description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.media'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='short_description',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='start_date',
            field=models.DateTimeField(default=promo.utils.default_start_datetime, null=True),
        ),
    ]
