# Generated by Django 4.1.7 on 2023-03-25 12:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_feature_rename_featured_dlc_is_featured_and_more'),
        ('promo', '0009_alter_promo_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='apply_to_game',
            field=models.ManyToManyField(blank=True, related_name='mtm', to='games.game'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 26, 0, 1), null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.media'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 0, 1), null=True),
        ),
    ]
