# Generated by Django 4.1.7 on 2023-03-28 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0010_alter_promo_apply_to_game_alter_promo_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 0, 1), null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 0, 1), null=True),
        ),
    ]
