# Generated by Django 4.1.7 on 2023-04-07 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0012_alter_promo_end_date_alter_promo_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 0, 1), null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 0, 1), null=True),
        ),
    ]
