# Generated by Django 4.1.7 on 2023-04-08 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0013_alter_promo_end_date_alter_promo_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 0, 1), null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 0, 1), null=True),
        ),
    ]
