# Generated by Django 4.1.7 on 2023-04-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=254, null=True, unique=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=6, null=True)),
                ('media_use', models.CharField(choices=[('COVER', 'Cover Image'), ('LANDING', 'Landing Image'), ('PREVIEW', 'Preview Media'), ('OTHER', 'Other Media')], default='OTHER', max_length=24)),
                ('media_ext', models.CharField(blank=True, max_length=6, null=True)),
                ('description', models.CharField(max_length=526, null=True)),
            ],
            options={
                'verbose_name_plural': 'Media',
            },
        ),
    ]
