# Generated by Django 4.1.7 on 2023-04-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
