# Generated by Django 4.1.7 on 2023-02-24 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_ratingset_esrb_rating_ratingset_esrb_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='ratingset',
            old_name='game_id',
            new_name='game',
        ),
    ]
