# Generated by Django 4.1.7 on 2023-02-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_rename_game_id_media_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='description',
            field=models.CharField(max_length=526, null=True),
        ),
    ]
