# Generated by Django 4.1.7 on 2023-02-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_media_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='media',
            field=models.ManyToManyField(blank=True, to='games.media'),
        ),
    ]
