# Generated by Django 4.1.7 on 2023-02-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_remove_media_game_game_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='media_type',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='name',
            field=models.CharField(default='Untitled$', max_length=254),
        ),
        migrations.AlterField(
            model_name='media',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
