# Generated by Django 4.1.7 on 2023-02-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_media_media_type_media_name_alter_media_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
