# Generated by Django 4.1.7 on 2023-02-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_media_media_type_alter_media_media_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name_plural': 'Media'},
        ),
        migrations.RenameField(
            model_name='dlc',
            old_name='publisher',
            new_name='publishers',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='platform',
            new_name='platforms',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='publisher',
            new_name='publishers',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='media',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='ratingset',
            old_name='esrb_rating',
            new_name='esrb_ratings',
        ),
    ]
