# Generated by Django 4.1.7 on 2023-02-25 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_media_options_rename_publisher_dlc_publishers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dlc',
            options={'verbose_name_plural': 'DLCs'},
        ),
        migrations.AddField(
            model_name='dlc',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='games.game'),
        ),
        migrations.AddField(
            model_name='dlc',
            name='media',
            field=models.ManyToManyField(blank=True, to='games.media'),
        ),
    ]
