# Generated by Django 4.1.7 on 2023-02-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_alter_dlc_options_dlc_game_dlc_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dlc',
            old_name='game',
            new_name='required_game',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='price',
            new_name='base_price',
        ),
        migrations.AddField(
            model_name='game',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='game',
            name='in_promo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
