# Generated by Django 4.1.7 on 2023-02-26 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_rename_game_dlc_required_game_and_more'),
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promo.promo'),
        ),
        migrations.AddField(
            model_name='game',
            name='promo_percentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
