# Generated by Django 4.1.7 on 2023-02-27 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
        ('games', '0012_game_promo_game_promo_percentage_game_promo_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dlc',
            old_name='price',
            new_name='base_price',
        ),
        migrations.RenameField(
            model_name='dlc',
            old_name='publishers',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='publishers',
            new_name='publisher',
        ),
        migrations.AddField(
            model_name='dlc',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='dlc',
            name='in_promo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='dlc',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promo.promo'),
        ),
        migrations.AddField(
            model_name='dlc',
            name='promo_percentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dlc',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='slug',
            field=models.SlugField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='slug',
            field=models.SlugField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='dlc',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='esrbrating',
            name='slug',
            field=models.SlugField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='platform',
            name='slug',
            field=models.SlugField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='slug',
            field=models.SlugField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=254, null=True),
        ),
    ]
