# Generated by Django 4.1.7 on 2023-02-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_rename_price_dlc_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='media_ext',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=6, null=True),
        ),
    ]
