# Generated by Django 4.1.7 on 2023-03-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_media_media_ext_alter_media_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='esrbrating',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='media',
            name='media_use',
            field=models.CharField(choices=[('COVER', 'Cover Image'), ('LANDING', 'Landing Image'), ('PREVIEW', 'Preview Media'), ('OTHER', 'Other Media')], default='OTHER', max_length=24),
        ),
        migrations.AddField(
            model_name='platform',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
