# Generated by Django 4.1.7 on 2023-03-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_esrbrating_image_media_media_use_platform_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='promo_percentage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
