# Generated by Django 4.1.7 on 2023-03-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_alter_game_promo_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dlc',
            name='promo_price',
        ),
        migrations.RemoveField(
            model_name='game',
            name='promo_price',
        ),
        migrations.RemoveField(
            model_name='media',
            name='media_url',
        ),
        migrations.AddField(
            model_name='dlc',
            name='carousel',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='dlc',
            name='featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='carousel',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='dlc',
            name='promo_percentage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
