# Generated by Django 4.1.7 on 2023-03-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_alter_developer_slug_alter_dlc_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=254, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='dlc',
            old_name='featured',
            new_name='is_featured',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='featured',
            new_name='is_featured',
        ),
        migrations.AddField(
            model_name='dlc',
            name='features',
            field=models.ManyToManyField(to='games.feature'),
        ),
        migrations.AddField(
            model_name='game',
            name='features',
            field=models.ManyToManyField(to='games.feature'),
        ),
    ]
