# Generated by Django 4.1.7 on 2023-04-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_userrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlc',
            name='genres',
            field=models.ManyToManyField(to='games.genre'),
        ),
        migrations.AddField(
            model_name='dlc',
            name='platforms',
            field=models.ManyToManyField(to='games.platform'),
        ),
        migrations.AlterField(
            model_name='dlc',
            name='carousel',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='dlc',
            name='is_featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='dlc',
            name='name',
            field=models.CharField(default='CHANGEME', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
