# Generated by Django 4.1.7 on 2023-04-08 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0024_dlc_genres_dlc_platforms_alter_dlc_carousel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingset',
            name='dlc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.dlc'),
        ),
        migrations.AlterField(
            model_name='ratingset',
            name='game',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.game'),
        ),
    ]
