# Generated by Django 4.1.7 on 2023-04-10 17:20

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0025_ratingset_dlc_alter_ratingset_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='country',
            field=django_countries.fields.CountryField(default='GB', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developer',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='developer',
            name='established',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developer',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='developer',
            name='official_site',
            field=models.URLField(default='https://ci-ms4-gamebox.herokuapp.com', verbose_name='Official Website'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platform',
            name='country',
            field=django_countries.fields.CountryField(default='GB', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platform',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='platform',
            name='established',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platform',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='platform',
            name='official_site',
            field=models.URLField(default='https://ci-ms4-gamebox.herokuapp.com', verbose_name='Official Website'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='country',
            field=django_countries.fields.CountryField(default='GB', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='publisher',
            name='established',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='publisher',
            name='official_site',
            field=models.URLField(default='https://ci-ms4-gamebox.herokuapp.com', verbose_name='Official Website'),
            preserve_default=False,
        ),
    ]
