# Generated by Django 4.1.7 on 2023-04-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0026_developer_country_developer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlc',
            name='storyline',
            field=models.TextField(default=''),
        ),
    ]
