# Generated by Django 4.1.7 on 2023-04-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0027_dlc_storyline'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='storyline',
            field=models.TextField(default=''),
        ),
    ]
