# Generated by Django 4.1.7 on 2023-04-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0028_game_storyline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlc',
            name='storyline',
            field=models.TextField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='game',
            name='storyline',
            field=models.TextField(default='', max_length=1024),
        ),
    ]
