# Generated by Django 4.1.7 on 2023-04-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0010_alter_promo_active_alter_promo_carousel_and_more'),
        ('home', '0001_initial'),
        ('games', '0030_alter_userrating_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.RemoveField(
            model_name='dlc',
            name='media',
        ),
        migrations.RemoveField(
            model_name='game',
            name='media',
        ),
        migrations.AddField(
            model_name='dlc',
            name='media',
            field=models.ManyToManyField(to='home.media'),
        ),
        migrations.AddField(
            model_name='game',
            name='media',
            field=models.ManyToManyField(to='home.media'),
        ),
    ]
