# Generated by Django 4.1.7 on 2023-04-23 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0033_remove_platform_icon_alter_dlc_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingset',
            name='esrb_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.esrbrating'),
        ),
        migrations.AlterField(
            model_name='ratingset',
            name='pegi_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.pegirating'),
        ),
    ]
